# Generated by Django 3.1 on 2020-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tag',
        ),
        migrations.AddField(
            model_name='todo',
            name='tag',
            field=models.ManyToManyField(null=True, to='myapp.Tag'),
        ),
    ]
