# Generated by Django 3.1 on 2020-09-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200830_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tag',
            new_name='tags',
        ),
    ]
